### ISSUE TITLE
No Such Module for GTMOAuth2

### ISSUE THREAD

**Issue by andrewbihl** [jmbremer/GAuthorizer#1]
It appears that including 
`pod 'GTMAppAuth'`
in the Podfile does not bring in GTMOAuth2 which is needed for GAuthorizer.swift. This causes an error after following the instructions in the README which say to remove the framework.

@jmbremer

**Comment by jmbremer** [comment]
No idea, how I came to leave that in there. Removed now. Sorry. It's not needed as described in the README. My production code, which I extracted this from, doesn't have this and the pod is also not included indirectly through another pod. Thanks for pointing out the obvious inconsistency.
