### ISSUE TITLE
The GAuthorizer class fails to compile

### ISSUE THREAD

**Issue by Daredevll** [jmbremer/GAuthorizer#3]
Hi, as the topic states - the file fails to compile with "User of unresolved identifier 'Config'" on lines 61 and 62 and 78. Now I've figured out the redirectURI and clientID, but can't figure the issuer...

**Comment by Daredevll** [comment]
After a dig in the obj-c code in AppAuth lib I've figured it out [here](https://github.com/openid/AppAuth-iOS), but it'd be pretty nice if you include these constants in the file so it'd be much clearer.

**Comment by jmbremer** [comment]
Sorry for the oversight and thus wasting your time! Added the missing values, which I configured outside obviously. (Not tested in context yet. Sorry. Hope it's working.)

The issuer, right now, should be "https://accounts.google.com". The other two values are specific to your app/Google, as you likely learned already.

Let me know, if this still causes you problems.
